"""Reporter — writes scan results to output volume."""

from __future__ import annotations

import json
from pathlib import Path

from agent.patcher import PatchResult
from agent.scanner import Finding


class Reporter:
    """Generates output files: report.json, summary.md, timing.json."""

    def __init__(self, output_path: Path, run_id: str):
        self.output_path = output_path
        self.run_id = run_id

    def run(
        self,
        findings: list[Finding],
        patches: list[PatchResult],
        timing: dict[str, float],
    ) -> None:
        """Write all report files."""
        self._write_report_json(findings, patches, timing)
        self._write_summary_md(findings, patches, timing)
        self._write_timing_json(timing)

    def _write_report_json(
        self, findings: list[Finding], patches: list[PatchResult], timing: dict[str, float]
    ) -> None:
        """Write the full structured JSON report."""
        report = {
            "run_id": self.run_id,
            "total_findings": len(findings),
            "total_patches": len(patches),
            "findings": [f.to_dict() for f in findings],
            "patches": [p.to_dict() for p in patches],
            "timing": timing,
            "severity_breakdown": self._severity_breakdown(findings),
        }

        report_path = self.output_path / "report.json"
        report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
        print(f"    → {report_path}")

    def _write_summary_md(
        self, findings: list[Finding], patches: list[PatchResult], timing: dict[str, float]
    ) -> None:
        """Write a human-readable Markdown summary."""
        total_time = sum(timing.values())
        severity_counts = self._severity_breakdown(findings)

        lines = [
            f"# QIP Scan Summary — {self.run_id}",
            "",
            f"**Total findings:** {len(findings)}  ",
            f"**Patches generated:** {len(patches)}  ",
            f"**Scan duration:** {total_time:.1f}s  ",
            "",
            "## Severity Breakdown",
            "",
            f"| Severity | Count |",
            f"|----------|-------|",
            f"| 🔴 Critical | {severity_counts.get('critical', 0)} |",
            f"| 🟠 High | {severity_counts.get('high', 0)} |",
            f"| 🟡 Medium | {severity_counts.get('medium', 0)} |",
            f"| 🔵 Low | {severity_counts.get('low', 0)} |",
            "",
            "## Findings",
            "",
            "| CVE | Component | Severity | CVSS | Fix Available |",
            "|-----|-----------|----------|------|---------------|",
        ]

        for f in findings:
            fix = f"✅ {f.fixed_version}" if f.fixed_version else "❌ None"
            lines.append(f"| {f.cve_id} | {f.component}@{f.version} | {f.severity} | {f.cvss_score} | {fix} |")

        if patches:
            lines.extend([
                "",
                "## Generated Patches",
                "",
                "| Patch | CVE | Component | Type | Confidence | Tests |",
                "|-------|-----|-----------|------|------------|-------|",
            ])
            for p in patches:
                test_icon = {"pass": "✅", "fail": "❌", "skip": "⚠️"}.get(p.test_result, "?")
                lines.append(
                    f"| {p.patch_file} | {p.cve_id} | {p.component} | "
                    f"{p.fix_type} | {p.confidence} | {test_icon} |"
                )

        lines.extend([
            "",
            "---",
            f"*Generated by Quantum Infinity Patcher*",
        ])

        summary_path = self.output_path / "summary.md"
        summary_path.write_text("\n".join(lines), encoding="utf-8")
        print(f"    → {summary_path}")

    def _write_timing_json(self, timing: dict[str, float]) -> None:
        """Write timing data."""
        timing_data = {
            "run_id": self.run_id,
            "total_seconds": sum(timing.values()),
            "stages": timing,
        }
        timing_path = self.output_path / "timing.json"
        timing_path.write_text(json.dumps(timing_data, indent=2), encoding="utf-8")

    def _severity_breakdown(self, findings: list[Finding]) -> dict[str, int]:
        """Count findings by severity."""
        counts: dict[str, int] = {}
        for f in findings:
            counts[f.severity] = counts.get(f.severity, 0) + 1
        return counts
